modLoader = "javafml"
loaderVersion = "[47,)"
license = "Custom"

[[mods]]
modId = "herbalbrews"
version = "${version}"
displayName = "[Let's Do] HerbalBrews"
authors = "satisfy"
description = '''
New Flowers, new crafting Stations, Tea
'''
logoFile = "pack.png"

[[dependencies.herbalbrews]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
