modLoader = "javafml"
loaderVersion = "[47,)"
source = "https://github.com/satisfyu/HerbalBrews"
issueTrackerURL = "https://github.com/satisfyu/Let-s-Do-Hub"
license = "Custom"

[[mods]]
modId = "herbalbrews"

version = "${version}"
displayName = "[Let's Do] HerbalBrews"

credits = "MissLilitu"
authors = "satisfy"
description = '''
Brew your bliss – discover new flowers, craft unique stations, and master the art of tea-making.
'''
logoFile = "pack.png"

[[dependencies.herbalbrews]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.herbalbrews]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
